apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: manshu123/auth-service
          env:
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: messaging
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-access-key
                  key: AWS_ACCESS_KEY
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-bucket-name
                  key: AWS_BUCKET_NAME
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-key
                  key: AWS_SECRET_KEY
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: database-host
                  key: DATABASE_HOST
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-username
                  key: DATABASE_USERNAME
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: database-name
                  key: DATABASE_NAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password
                  key: DATABASE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-cluserip-srv
spec:
  type: LoadBalancer
  selector:
    app: auth-service
  ports:
    - name: auth-service
      protocol: TCP
      port: 4000
      targetPort: 4000
