apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
        - name: message-service
          image: manshu123/message-service
          ports:
            - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: message-service-cluserip-srv
spec:
  type: LoadBalancer
  selector:
    app: message-service
  ports:
    - name: message-service
      protocol: TCP
      port: 4002
      targetPort: 4002
